# Generated by plugins/tandem/install.sh — shared env for tandem (Cursor + OpenCode + CLI).
# Re-run install.sh after moving the repo clone.
export TANDEM_PLUGIN_ROOT="@TANDEM_ROOT@"
export TANDEM_DATA_DIR="${TANDEM_DATA_DIR:-@DATA_DIR@}"
# Optional: set TANDEM_CHROME_BIN to override autodetect (e.g. WSL bundled Chrome).
# export TANDEM_CHROME_BIN="..."
# Optional WSL/Linux deps (uncomment if needed):
# export LD_LIBRARY_PATH="...${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
